language: java
jdk:
  - openjdk8
  - oraclejdk8
install: true
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'CREATE USER dembesi PASSWORD dembesi SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE dembesi;' -U dembesi
script:
  - ./mvnw clean install
